# **_📐 NUMPY 📐_**

#### **🔺O que é a biblioteca "Numpy"?🔺**

- *Numpy é uma biblioteca muito utilizado na área de Data Science, Machine Learning, Inteligência Artificial, Deep Learning, etc.
**O seu principal objetivo é manipular/alterar dados em grande escala.** Outrossim, **utiliza-se "arrays" de diversas dimensões.** Logo,
cada dimensão tem suas diferenças entre si.*
- *Vale ressaltar, que quando comparamos com listas tradicionais no Python, **os "arrays" do Numpy são muito mais rápidas e
eficientes.** Haja vista que um "array" em Numpy, **só pode ter um único tipo de valor**, sendo assim, não há a necessidade de verificar
os tipos de cada elemento da lista.*
- *Outrossim, os conceitos de Arrays só servem para conseguimos entender melhor, porém, para a máquina, não funcionará dessa forma.* **Cada eixo do Array pode ser interpretado de formas diferentes dependendo do contexto inserido.**

#### **📌Qual o principal propósito do Numpy na Área de Dados?📌**

- *O principal propósito do NumPy na Área de Dados* **é manipular e alterar grandes volumes de dados de forma rápida e eficiente.**
- *Além disso, o Numpy **é a base de diversas bibliotecas de Dados.** Por exemplo, o Pandas.*

#### **⬆Exportando a biblioteca Numpy⬆**

In [1]:
import numpy as np

*Importei a biblioteca "numpy" e coloquei um apelido para ele. Chama-se "np". Vale ressaltar que na documentação oficial do Numpy, é recomendado colocar "np" como apelido.*

#### **📏 Array em Numpy📏**

**Para criar um array no Numpy é só usar o comando "np.array(número_de_eixos[elementos])"**

In [4]:
array_a = np.array([1, 2, 3, 4])
print(array_a)

[1 2 3 4]


*É necessário lembrar que um array no Numpy é* **obrigatório ser homogêneo!** *Ou seja,* **converte-se todos os elementos dentro do
array para um único tipo de valor.**

In [9]:
array_b = np.array([1, 1.2, 3, 4.5])
print(array_b)

[1.  1.2 3.  4.5]


*Percebe-se que criei outro array e dentro dela, coloquei 2 tipos de elementos diferentes. O numpy converteu todos para float.*

#### **🔢Tipos de Array🔢**

##### **Array 1D(Vetor)1️⃣**

In [8]:
vector = np.array([1, 2])
print(vector.ndim) # Verifica quantas dimensões tem o array "vector".
print(vector.shape) # Verifica qual é a estrutura do array "vector".
print(vector)

1
(2,)
[1 2]


**Um Array 1D pode ser definido conceitualmente uma "lista". Ou seja, é representado apenas por um eixo, o qual pode colocar uma sequência de valores. Outrossim, pode-se chamar vetores.**

##### **Array 2D(Matriz)2️⃣**

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim) # Verifica quantas dimensões tem o array "matrix".
print(matrix.shape) # Verifica qual é a estrutura do array "matrix".
print(matrix)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


**Um array 2D é uma estrutura bidimensional que pode ser visualizada como uma tabela ou grade retangular.
Ele possui dois eixos ortogonais, comumente interpretados como linhas (eixo vertical) e colunas (eixo horizontal),
dependendo do contexto do problema. Outrossim, pode-se chamar matrizes.**

**_Array 3D(Tensor)3️⃣_**

In [12]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor.ndim) # Verifica quantas dimensões tem o array "tensor".
print(tensor.shape) # Verifica qual é a estrutura do array "tensor".
print(tensor)

3
(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


**Um array 3D é uma estrutura tridimensional formada por três eixos. Conceitualmente, pode ser visto como uma pilha de
matrizes ou um volume de dados. O significado de cada eixo depende do contexto do problema; em aplicações de visão
computacional, por exemplo, é comum associá-los a altura, largura e canais. Outrossim, pode-se chamar tensor.**

**Array 4D(Tensor)4️⃣**

In [13]:
tensor = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(tensor.ndim) # Verifica quantas dimensões tem o array "tensor".
print(tensor.shape) # Verifica qual é a estrutura do array "tensor".
print(tensor)

4
(1, 1, 3, 3)
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


**Um array 4D é uma estrutura tetradimensional formada por quatro eixos. Conceitualmente, pode ser interpretado como um
lote de arrays 3D. O significado de cada eixo não é fixo e depende do contexto da aplicação. Em processamento de imagens, é
comum interpretá-los como batch, altura, largura e canais. Outrossim, pode-se chamar tensor.**

#### **📑Funções shape(), reshape(), dtype() e ndim()📑**

*ndim():*

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The array 'a' have {a.ndim} dimensions!")

The array 'a' have 2 dimensions!


- **A função "ndim()" mostra a quantidade de dimensões que um determinado array tem.**
- **Tem o propósito de auxiliar na inspeção de eixos que um determinado array tem.**

*dtype():*

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The type of array is {a.dtype}!")

The type of array is int64!


- **A função "dtype()" mostra qual é o tipo do array. Ou seja, dependendo dos elementos guardados no array, o "dtype()" pode
variar. Podendo ser um "int64", "int32", "int16", "float64", "float32", "float16" etc.**
- **O "dtype()" é importante para otimizar desempenhos e inspecionar informações de um array.**

shape():

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The array shape is {a.shape}")

The array shape is (3, 3)


- **A função "shape()" mostra qual é a estrutura do array. Ou seja, dependendo de um array, o "shape()" pode variar.**
- **O propósito do "shape()" é inspecionar a estrutura de um array, sendo assim, uma ótima ferramenta para verificação.**

reshape():

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Reshaping an array 2D to 1D: {a.reshape(9,)} ")

Reshaping an array 2D to 1D: [1 2 3 4 5 6 7 8 9] 


- **A função "reshape()" não manipula os dados diretamente. Porém, pode mudar a visão enxergada de um determinado array.
Ou seja, essa funcionalidade muda a estrutura de um array.**
- **Sendo assim, o método reshape() permite reorganizar a forma de um array, possibilitando observar e trabalhar com os mesmos dados sob diferentes perspectivas estruturais, sem alterar os valores armazenados.**

#### **📖Funções arange(), linspace(), zeros() e ones()📖**

arange():

In [14]:
a = np.arange(1, 11)
print(f"""Building an array with the function np.arange:
{a}""")

Building an array with the function np.arange: 
[ 1  2  3  4  5  6  7  8  9 10]


- **A função "arange()" tem uma funcionalidade parecida com o "range()" do python. O qual, necessita-se de um ponto de partida, o ponto de parada e o passo que vai pecorrer.**
- **O principal objetivo da função "arange()" é para simulações simples, criação rápida de arrays e índices.**

linspace():

In [15]:
a = np.linspace(0, 2, 10)
print(f"""Building an array with the function np.linspace:
{a}""")

Building an array with the function np.linspace:
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


- **A função "linspace()" entrega uma quantidade de valores entre dois números selecionados. Tendo a seguinte estrutura:
 np.linspace(num_inicial, num_final, qnt_de_elementos)**
 - **O principal objetivo da função "linspace()" é para a criação de gráficos, ML, normalização etc.**

zeros():

In [21]:
a = np.zeros((3, 3))
print(f"""Building an array with the function np.zeros:
{a}""")

Building an array with the function np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


- **A função "zeros()" entrega apenas elementos com valor zero e o seu shape pode ser personalizado conforme
o contexto.**
- **"zeros()" é bastante utilizado em inicialização, buffers, matrizes vazias e placeholders.**

ones():

In [22]:
a = np.ones((3, 3))
print(f"""Building an array with the function np.ones:
{a}""")

Building an array with the function np.ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- **A função "ones()" entrega apenas elementos com valor um e o seu shape pode ser personalizado conforme o contexto.**
- **"ones()" é bastante utilizado em pesos inicias, máscaras, normalizações e operações matemáticas.**

#### **✂️Indexação Básica e Avançada✂️**

*Antes de entrar no assunto bruto, é necessário distinguir a diferença entre View x Copy!*
- **View:** é uma nova forma de enxergar os dados na memória. Ou seja, modifica o elemento raíz, sendo assim,
não gera uma cópia.
- **Copy:** é uma cópia dos dados já existentes na memória. Ou seja, não modifica o elemento raíz diretamente, sendo assim,
cria-se novos dados na memória.

##### **Indexação Básica**
- *A indexação básica retorna uma view dos dados originais (quando possível), de modo que alterações feitas na seleção refletem no array raiz.*

*Indexing/Indexação:*

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

indexing_an_element = a[2, 0]

print(f"""There are the indexed element founded:
{indexing_an_element}""")

There are the indexed element founded:
7


In [54]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

view_element = a[2, 1] = 0

print(view_element)
print("---------")
print(a) # Percebe-se que altera diretamente o array raíz, sendo assim, retorna-se uma "view".

0
---------
[[1 2 3]
 [4 5 6]
 [7 0 9]]


- **A indexação tem o principal propósito de pegar valores isolados e selecionados. Outrossim, retorna-se uma "view" dos dados originais, de modo que alterações feitas na indexação refletem diretamente na array raíz.**
- **A indexação é importante para determinar e organizar dados.**

Slicing/Fatiamento:

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

slicing_element = a[0:2, :]

print(f"""There are the slicing elements founded:
{slicing_element}""")

There are the slicing elements founded:
[[1 2 3]
 [4 5 6]]


In [52]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

view_element = a[:, 0:2] = 0
print(view_element)
print("---------")
print(a) # Percebe-se que altera diretamente o array raíz, sendo assim, retorna-se uma "view".

0
---------
[[0 0 3]
 [0 0 6]
 [0 0 9]]


- **O fatiamento tem o principal propósito é selecionar intervalos de um conjunto de valores. Outrossim, cria-se uma "view" de um dado já existente na memória. Ou seja, altera a raíz dos dados diretamente, sem criar cópias.**
- **A sua importância é trabalhar com subconjuntos organizados, criar features, criar lotes, processar janela de dados etc.**

##### **Indexação avançada**
- *Retorna sempre uma cópia.*

Boolean Mask/Máscara Booleana:

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mask = a[a > 3]

print(f"""There are the masking elements founded:
{mask}""")

There are the masking elements founded:
[4 5 6 7 8 9]


In [49]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

copy_element = a[a > 4]
b = copy_element[:] = 0

print(copy_element)
print("-----------")
print(a) # Percebe-se que não foi alterado nenhum valor do array raíz. Logo, criou-se uma cópia.

[0 0 0 0 0]
-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- **O boolean mask tem o principal propósito de selecionar valores baseados em condições. Outrossim, cria-se uma cópia de
um dado já existente na memória. Logo, cria dados a partir de um array existente.**
- **A sua importância é filtrar e limpar dados.**

*Fancy Indexing/Indexação Sofisticada:*

In [55]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

fancy_indexing_an_element = a[[0, 2]] # É necessário ter ao menos essa estrutura para fazer o fancy indexing.
print(f"""I am using the fancy indexing element:
{fancy_indexing_an_element}""")

I am using the fancy indexing element: 
[[1 2 3]
 [7 8 9]]


In [46]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

copy_element = a[[0, 1]] # É necessário ter ao menos essa estrutura para fazer o fancy indexing.
b = copy_element[:] = 0

print(copy_element)
print("---------")
print(a) # Percebe-se que não foi alterado nenhum valor do array raíz. Logo, criou-se uma cópia.

[[0 0 0]
 [0 0 0]]
---------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- **A indexação sofisticada tem o principal propósito de fazer uma cópia do array raíz, usando indexação. Vale ressaltar, que pode também usar slicing.**
- **Ela expande drasticamente o poder de seleção e reorganização de dados.**

In [58]:
# Usando o fancy indexing com slicing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

fancy_indexing_and_slicing_elements = a[[0, 2], :2]
print(f"""I am using fancy indexing and slicing in the same time:
{fancy_indexing_and_slicing_elements}""")

I am using fancy indexing and slicing in the same time: 
[[1 2]
 [7 8]]


##### **A indexação, indexação sofisticada, fatiamento e máscara booleana manipulam dados?**

- *Indexação, fatiamento (slicing), fancy indexing e máscaras booleanas não alteram os dados por si só.
Eles apenas selecionam elementos. A manipulação ocorre quando há atribuição.*

**Exemplos:**

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0, 2] = 0
print(a)

[[1 2 0]
 [4 5 6]
 [7 8 9]]


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[:, 2] = 0
print(a)

[[1 2 0]
 [4 5 0]
 [7 8 0]]


#### **_Operações, Broadcasting e Dot Product_**

- **O NumPy proporciona grande agilidade na realização de cálculos em larga escala,
pois os arrays são homogêneos e armazenados de forma contígua na memória.
Dessa forma, não há necessidade de verificar o tipo de dado de cada elemento,
o que torna as operações vetorizadas significativamente mais eficientes
do que abordagens tradicionais em Python puro.**


##### **Operações Matemáticas Básicas Entre Arrays**

- Nas operações matemáticas básicas do NumPy, os cálculos são realizados
de forma vetorizada, ou seja, elemento a elemento entre os arrays,
desde que suas formas (shapes) sejam compatíveis.


Somando Arrays(+):

In [8]:
a = np.ones((3, 3))
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a + b)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


Subtraindo Arrays(-):

In [12]:
a = np.ones((3, 3))
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a - b)

[[ 0. -1. -2.]
 [-3. -4. -5.]
 [-6. -7. -8.]]


Multiplicando Arrays(*):

In [13]:
a = np.ones((3, 3))
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a * b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Dividindo Arrays(/):

In [14]:
a = np.ones((3, 3))
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a / b)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


Potenciação com Arrays(**):

In [15]:
a = np.ones((3, 3))
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a ** b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Em todos os exemplos acima, os arrays possuem o mesmo shape, permitindo que o NumPy realize as operações matemáticas de forma direta e elemento a elemento, sem a necessidade de ajustes adicionais.**

##### **Broadcasting**

*Surge-se a seguinte pergunta: E se houver a necessidade de fazer operações aritméticas entre arrays com shapes diferentes?*

- **É nesse contexto que surge o broadcasting, um mecanismo do NumPy que permite realizar operações aritméticas entre arrays de shapes diferentes, desde que respeitem determinadas regras.**

##### **Regra de Compatibilidade do Broadcasting:**

Para que o broadcasting funcione corretamente, o NumPy segue uma regra de compatibilidade entre os shapes dos arrays.
Essa regra consiste em comparar as dimensões dos arrays da direita para a esquerda, eixo por eixo.
Em cada comparação, duas dimensões são consideradas compatíveis se:

- **forem iguais, ou**

- **uma delas for igual a 1.**

Caso nenhuma dessas condições seja atendida, o NumPy não consegue determinar como alinhar os dados, e a operação gera um erro. Ou seja, **quando um array possui uma dimensão igual a 1, o NumPy não cria cópias reais dos dados.
Em vez disso, ele reutiliza virtualmente esse valor ao longo da dimensão necessária durante o cálculo.**

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([2, 4, 6])

print(a.shape)
print(b.shape)
print("----------------------------------------------------")

print(f"""There are the results of the broadcasting operation:
{a + b}""")

(3, 3)
(3,)
----------------------------------------------------
There are the results of the broadcasting operation:
[[ 3  6  9]
 [ 6  9 12]
 [ 9 12 15]]


In [33]:
a = np.ones((2, 3))
b = np.array([10])

print(b.shape)
print("----------------------------------------------------")

print(f"""There are the results of the broadcasting operation:
{a + b}""")

(1,)
----------------------------------------------------
There are the results of the broadcasting operation:
[[11. 11. 11.]
 [11. 11. 11.]]


**Esses exemplos demonstram como o broadcasting permite realizar operações entre arrays de diferentes shapes sem a necessidade de loops explícitos, reutilizando valores de forma virtual e eficiente durante o cálculo.**

##### **Dot Product(@)**

- **O operador @ no NumPy representa o produto matricial, também conhecido como dot product. Diferentemente das operações aritméticas básicas, essa operação não é realizada elemento por elemento e não utiliza broadcasting da mesma forma.**

Fazendo alguns exemplos de Dot Product(@):

Array 2D x Array 1D:

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Três colunas
b = np.array([2, 4, 6]) # Três linhas

# Verificando os "shapes" do array "a" e "b"...
print(a.shape)
print(b.shape) # O numpy vai entender que será (3, 1) durante o cálculo
print("-----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(3, 3)
(3,)
-----------------
There are the results of dot product operation:
[ 28  64 100]


In [12]:
a = np.ones((2, 3), dtype=int) # Mudando o dtype para "int", chama-se upcasting
b = np.array([2, 4, 6])

# Verificando os "shape" do array "b"...
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(3,)
----------------
There are the results of dot product operation:
[12 12]


Array 2D x Array 2D:

In [17]:
a = np.array([[10, 20, 30]]) # Três colunas
b = np.array([[1, 2], [4, 5], [7, 8]]) # Três linhas

# Verificando os "shapes" do arrays "a" e "b"...
print(a.shape)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(1, 3)
(3, 2)
----------------
There are the results of dot product operation:
[[300 360]]


In [16]:
a = np.ones((1, 2), dtype=int) # Mudando o dtype para "int", chama-se upcasting
b = np.array([[2, 4, 6], [8, 10, 12]])

# Verificando o "shape" do array "b"...
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(2, 3)
----------------
There are the results of dot product operation:
[[10 14 18]]


Array 2D x Array 3D:

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Três colunas e Um canal
b = np.array([[[3, 4], [6, 7], [9, 10]]]) # Duas linhas e Um canal

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape) # O numpy durante o cálculo irá entender o shape dessa forma: (1, 3, 3)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(3, 3)
(1, 3, 2)
----------------
There are the results of dot product operation:
[[[ 42  48]
  [ 96 111]
  [150 174]]]


In [25]:
a = np.array([[2, 4], [6, 8]]) # Duas colunas e Um canal
b = np.array([[[5, 10], [15, 20]], [[20, 25], [30, 35]], [[40, 45], [50, 55]]]) # Duas colunas e Três canais

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape) # O numpy durante o cálculo irá entender o shape dessa forma: (1, 2, 2)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(2, 2)
(3, 2, 2)
----------------
There are the results of dot product operation:
[[[ 70 100]
  [150 220]]

 [[160 190]
  [360 430]]

 [[280 310]
  [640 710]]]


Array 3D x 3D:

In [27]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # Três colunas e Um canal
b = np.array([[[10, 20], [30, 40], [50, 60]]]) # Três linhas e Um canal

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")


(1, 3, 3)
(1, 3, 2)
----------------
There are the results of dot product operation:
[[[ 220  280]
  [ 490  640]
  [ 760 1000]]]


In [31]:
a = np.ones((5, 2, 2), dtype=int) # Mudando o dtype para "int", chama-se upcasting
b = np.array(([[[10, 20], [30, 40]]]))

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(5, 2, 2)
(1, 2, 2)
----------------
There are the results of dot product operation:
[[[40 60]
  [40 60]]

 [[40 60]
  [40 60]]

 [[40 60]
  [40 60]]

 [[40 60]
  [40 60]]

 [[40 60]
  [40 60]]]


Array 3D x Array 4D:

In [34]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # Três colunas e Um canal
b = np.array([[[[5, 10], [15, 20], [25, 30]]]]) # Três Linhas e Um canal

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape) # Durante o cálculo, o numpy entenderá (1, 1, 3, 3)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(1, 3, 3)
(1, 1, 3, 2)
----------------
There are the results of dot product operation:
[[[[110 140]
   [245 320]
   [380 500]]]]


In [36]:
a = np.array([[[2, 4], [6, 8]], [[10, 20], [30, 40]]])
b = np.ones((1, 2, 2, 3), dtype=int) # Mudando o dtype para int, esse processo chama upcasting

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape) # Durante o cálculo, o numpy entenderá (1, 2, 2, 2)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(2, 2, 2)
(1, 2, 2, 3)
----------------
There are the results of dot product operation:
[[[[ 6.  6.  6.]
   [14. 14. 14.]]

  [[30. 30. 30.]
   [70. 70. 70.]]]]


Array 4D x Array 4D:

In [38]:
a = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]]) # Três colunas, Um canal e Um batch
b = np.array([[[[10, 20], [40, 50,], [70, 80]]]]) # Três linhas, Um canal e Um batch

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(1, 1, 3, 3)
(1, 1, 3, 2)
----------------
There are the results of dot product operation:
[[[[ 300  360]
   [ 660  810]
   [1020 1260]]]]


In [39]:
a = np.array([[[[2, 4], [6, 8]], [[10, 12], [14, 16]], [[18, 20], [22, 24]]]]) # Duas colunas, Três canais e Um batch
b = np.zeros((1, 1, 2, 5), dtype=int) # Mudando o dtype para int, esse proceso chama upcasting

# Verificando os "shapes" dos arrays "a" e "b"...
print(a.shape)
print(b.shape)
print("----------------")
print(f"""There are the results of dot product operation:
{a @ b}""")

(1, 3, 2, 2)
(1, 1, 2, 5)
----------------
There are the results of dot product operation:
[[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


##### **Como fazer o Dot Product em Qualquer Array**
- **O produto escalar (ou dot product) é uma operação fundamental em álgebra linear que combina dois vetores para produzir um único número (um escalar). Ele representa a projeção de um vetor sobre o outro.**
- **Em termos simples, para dois vetores, ele é a soma dos produtos dos seus elementos correspondentes.**

##### **Como o NumPy calcula o Dot Product?**

O NumPy oferece duas maneiras principais para calcular o produto escalar:
1.  A função `np.dot(a, b)`
2.  O operador `@` (preferencial para multiplicação de matrizes a partir do Python 3.5)

Ambos funcionam de maneira similar, mas o operador `@` é geralmente mais legível e moderno.

##### **Regra de Ouro do Dot Product**

Para que a operação de produto escalar entre dois arrays `a` e `b` seja possível, a **regra de compatibilidade** deve ser seguida:

> **O número de colunas do primeiro array (`a`) deve ser igual ao número de linhas do segundo array (`b`). O restante dos eixos deverão ser compatíveis via broadcasting.**

Visualmente:
- Se `a` tem shape `(M, N)`
- E `b` tem shape `(N, P)`
- O resultado terá shape `(M, P)`.

Vamos ver na prática!

##### **Exemplo 1: Produto Escalar de dois Vetores (Arrays 1D)**

Quando calculamos o produto escalar de dois vetores, o resultado é um escalar (um único número).

- Vetor `a` = `[1, 2]`
- Vetor `b` = `[3, 4]`
- Cálculo manual: `(1 * 3) + (2 * 4) = 3 + 8 = 11`

In [43]:
# Vetores (Arrays 1D)
vetor_a = np.array([1, 2])
vetor_b = np.array([3, 4])

# Seus shapes
print(f"Shape de vetor_a: {vetor_a.shape}")
print(f"Shape de vetor_b: {vetor_b.shape}")

# Calculando o produto escalar
dot_product_1d = vetor_a @ vetor_b

print(f"\nO produto escalar entre os vetores é: {dot_product_1d}")
print("O resultado é um escalar (um único número).")

Shape de vetor_a: (2,)
Shape de vetor_b: (2,)

O produto escalar entre os vetores é: 11
O resultado é um escalar (um único número).


##### **Exemplo 2: Produto Escalar de Matriz (2D) e Vetor (1D)**

Aqui, a regra de compatibilidade é crucial. Se a matriz tem shape `(M, N)`, o vetor deve ter `N` elementos.

- Matriz `a` (shape 2x3)
- Vetor `b` (3 elementos)
- O resultado será um vetor de `M` (ou seja, 2) elementos.

In [42]:
# Matriz 2D e Vetor 1D
matriz_a = np.array([[1, 2, 3],  # 2 linhas, 3 colunas
                     [4, 5, 6]])
vetor_b = np.array([7, 8, 9])   # 3 elementos

print(f"Shape da matriz_a: {matriz_a.shape}")
print(f"Shape do vetor_b: {vetor_b.shape}")

# A regra é satisfeita: 3 colunas em matriz_a == 3 elementos em vetor_b

# Calculando o produto escalar
dot_product_2d_1d = matriz_a @ vetor_b

print(f"\nO produto escalar entre a matriz e o vetor é: {dot_product_2d_1d}")
print(f"O shape do resultado é: {dot_product_2d_1d.shape}")

Shape da matriz_a: (2, 3)
Shape do vetor_b: (3,)

O produto escalar entre a matriz e o vetor é: [ 50 122]
O shape do resultado é: (2,)


##### **Exemplo 3: Produto Escalar de duas Matrizes (Arrays 2D)**

Este é o caso clássico de multiplicação de matrizes.

- Matriz `a` (shape 2x3)
- Matriz `b` (shape 3x2)
- O resultado será uma matriz de shape `(2, 2)`.

In [45]:
# Duas Matrizes 2D
matriz_a = np.array([[1, 2, 3],  # Shape (2, 3)
                     [4, 5, 6]])

matriz_b = np.array([[7, 8],     # Shape (3, 2)
                     [9, 10],
                     [11, 12]])

print(f"Shape da matriz_a: {matriz_a.shape}")
print(f"Shape da matriz_b: {matriz_b.shape}")

# A regra é satisfeita: 3 colunas em matriz_a == 3 linhas em matriz_b

# Calculando o produto escalar
dot_product_2d_2d = matriz_a @ matriz_b

print(f"\nO produto escalar entre as duas matrizes é:\n{dot_product_2d_2d}")
print(f"\nO shape da matriz resultante é: {dot_product_2d_2d.shape}")

Shape da matriz_a: (2, 3)
Shape da matriz_b: (3, 2)

O produto escalar entre as duas matrizes é:
[[ 58  64]
 [139 154]]

O shape da matriz resultante é: (2, 2)


**Resumindo, o produto escalar (`@`) é uma ferramenta poderosa para operações de álgebra linear. Apenas lembre-se da regra de ouro: o número de colunas do primeiro array deve ser igual ao número de linhas do segundo e o restante dos eixos deverão ser compatíveis via broadcasting.**
