# **_📐 NUMPY 📐_**

#### **_🔺O que é a biblioteca "Numpy"?🔺_**

- *_Numpy é uma biblioteca muito utilizado na área de Data Science, Machine Learning, Inteligência Artificial, Deep Learning, etc.
**O seu principal objetivo é manipular/alterar dados em grande escala.** Outrossim, **utiliza-se "arrays" de diversas dimensões.** Logo,
cada dimensão tem suas diferenças entre si._*
- *_Vale ressaltar, que quando comparamos com listas tradicionais no Python, **os "arrays" do Numpy são muito mais rápidas e
eficientes.** Haja vista que um "array" em Numpy, **só pode ter um único tipo de valor**, sendo assim, não há a necessidade de verificar
os tipos de cada elemento da lista._*
- *_Outrossim, os conceitos de Arrays só servem para conseguimos entender melhor, porém, para a máquina, não funcionará dessa forma._* **Cada eixo do Array pode ser interpretado de formas diferentes dependendo do contexto inserido.**

#### **_📌Qual o principal propósito do Numpy na Área de Dados?📌_**

- *_O principal propósito do NumPy na Área de Dados_* **é manipular e alterar grandes volumes de dados de forma rápida e eficiente.**
- *_Além disso, o Numpy **é a base de diversas bibliotecas de Dados.** Por exemplo, o Pandas._*

#### **_⬆Exportando a biblioteca Numpy⬆_**

In [2]:
import numpy as np

*_Importei a biblioteca "numpy" e coloquei um apelido para ele. Chama-se "np". Vale ressaltar que na documentação oficial do Numpy, é recomendado colocar "np" como apelido._*

#### **_📏 Array em Numpy📏_**

**_Para criar um array no Numpy é só usar o comando "np.array(número_de_eixos[elementos])"_**

In [4]:
array_a = np.array([1, 2, 3, 4])
print(array_a)

[1 2 3 4]


*_É necessário lembrar que um array no Numpy é_* **obrigatório ser homogêneo!** *_Ou seja,_* **converte-se todos os elementos dentro do
array para um único tipo de valor.**

In [9]:
array_b = np.array([1, 1.2, 3, 4.5])
print(array_b)

[1.  1.2 3.  4.5]


*_Percebe-se que criei outro array e dentro dela, coloquei 2 tipos de elementos diferentes. O numpy converteu todos para float._*

#### **_🔢Tipos de Array_🔢**

##### **_Array 1D(Vetor)1️⃣_**

In [8]:
vector = np.array([1, 2])
print(vector.ndim) # Verifica quantas dimensões tem o array "vector".
print(vector.shape) # Verifica qual é a estrutura do array "vector".
print(vector)

1
(2,)
[1 2]


**_Um Array 1D pode ser definido conceitualmente uma "lista". Ou seja, é representado apenas por um eixo, o qual pode colocar uma sequência de valores. Outrossim, pode-se chamar vetores._**

##### **_Array 2D(Matriz)2️⃣_**

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim) # Verifica quantas dimensões tem o array "matrix".
print(matrix.shape) # Verifica qual é a estrutura do array "matrix".
print(matrix)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


**_Um array 2D é uma estrutura bidimensional que pode ser visualizada como uma tabela ou grade retangular.
Ele possui dois eixos ortogonais, comumente interpretados como linhas (eixo vertical) e colunas (eixo horizontal),
dependendo do contexto do problema. Outrossim, pode-se chamar matrizes._**

**_Array 3D(Tensor)3️⃣_**

In [12]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor.ndim) # Verifica quantas dimensões tem o array "tensor".
print(tensor.shape) # Verifica qual é a estrutura do array "tensor".
print(tensor)

3
(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


**_Um array 3D é uma estrutura tridimensional formada por três eixos. Conceitualmente, pode ser visto como uma pilha de
matrizes ou um volume de dados. O significado de cada eixo depende do contexto do problema; em aplicações de visão
computacional, por exemplo, é comum associá-los a altura, largura e canais. Outrossim, pode-se chamar tensor._**

**_Array 4D(Tensor)4️⃣_**

In [13]:
tensor = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(tensor.ndim) # Verifica quantas dimensões tem o array "tensor".
print(tensor.shape) # Verifica qual é a estrutura do array "tensor".
print(tensor)

4
(1, 1, 3, 3)
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


**_Um array 4D é uma estrutura tetradimensional formada por quatro eixos. Conceitualmente, pode ser interpretado como um
lote de arrays 3D. O significado de cada eixo não é fixo e depende do contexto da aplicação. Em processamento de imagens, é
comum interpretá-los como batch, altura, largura e canais. Outrossim, pode-se chamar tensor._**

#### **_📑Funções shape(), reshape(), dtype() e ndim()📑_**

*_ndim():_*

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The array 'a' have {a.ndim} dimensions!")

The array 'a' have 2 dimensions!


- **_A função "ndim()" mostra a quantidade de dimensões que um determinado array tem._**
- **_Tem o propósito de auxiliar na inspeção de eixos que um determinado array tem._**

*_dtype():_*

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The type of array is {a.dtype}!")

The type of array is int64!


- **_A função "dtype()" mostra qual é o tipo do array. Ou seja, dependendo dos elementos guardados no array, o "dtype()" pode
variar. Podendo ser um "int64", "int32", "int16", "float64", "float32", "float16" etc._**
- **_O "dtype()" é importante para otimizar desempenhos e inspecionar informações de um array._**

shape():

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"The array shape is {a.shape}")

The array shape is (3, 3)


- **_A função "shape()" mostra qual é a estrutura do array. Ou seja, dependendo de um array, o "shape()" pode variar._**
- **_O propósito do "shape()" é inspecionar a estrutura de um array, sendo assim, uma ótima ferramenta para verificação._**

reshape():

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Reshaping an array 2D to 1D: {a.reshape(9,)} ")

Reshaping an array 2D to 1D: [1 2 3 4 5 6 7 8 9] 


- **_A função "reshape()" não manipula os dados diretamente. Porém, pode mudar a visão enxergada de um determinado array.
Ou seja, essa funcionalidade muda a estrutura de um array._**
- **_Sendo assim, o método reshape() permite reorganizar a forma de um array, possibilitando observar e trabalhar com os mesmos dados sob diferentes perspectivas estruturais, sem alterar os valores armazenados._**

#### **_Funções arange(), linspace(), zeros() e ones()_**

arange():

In [14]:
a = np.arange(1, 11)
print(f"""Building an array with the function np.arange:
{a}""")

Building an array with the function np.arange: 
[ 1  2  3  4  5  6  7  8  9 10]


- **_A função "arange()" tem uma funcionalidade parecida com o "range()" do python. O qual, necessita-se de um ponto de partida, o ponto de parada e o passo que vai pecorrer._**
- **_O principal objetivo da função "arange()" é para simulações simples, criação rápida de arrays e índices._**

linspace():

In [15]:
a = np.linspace(0, 2, 10)
print(f"""Building an array with the function np.linspace:
{a}""")

Building an array with the function np.linspace:
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


- **_A função "linspace()" entrega uma quantidade de valores entre dois números selecionados. Tendo a seguinte estrutura:
 np.linspace(num_inicial, num_final, qnt_de_elementos)_**
 - **_O principal objetivo da função "linspace()" é para a criação de gráficos, ML, normalização etc._**

zeros():

In [21]:
a = np.zeros((3, 3))
print(f"""Building an array with the function np.zeros:
{a}""")

Building an array with the function np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


- **_A função "zeros()" entrega apenas elementos com valor zero e o seu shape pode ser personalizado conforme
o contexto._**
- **_"zeros()" é bastante utilizado em inicialização, buffers, matrizes vazias e placeholders._**

ones():

In [22]:
a = np.ones((3, 3))
print(f"""Building an array with the function np.ones:
{a}""")

Building an array with the function np.ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- **_A função "ones()" entrega apenas elementos com valor um e o seu shape pode ser personalizado conforme o contexto._**
- **_"ones()" é bastante utilizado em pesos inicias, máscaras, normalizações e operações matemáticas._**